language: java
jdk:
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk11
  - openjdk11
  - oraclejdk13
  - openjdk13
  #- oraclejdk14
  #- openjdk14
  #- oraclejdk15
  #- openjdk15
addons:
  sonarcloud:
    organization: "kmindi-github" # the key of the org you chose at step #3
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
  - chmod +x gradlew
script:
  # other script steps might be done before running the actual SonarQube analysis
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - sonar-scanner
